spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost/order-service
    username: user
    password: user
    jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: http://localhost:8716/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
  endpoint:
    health:
      show-details: always

#Resilinece4j Properties
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

  timelimiter:
    instances:
      inventory:
        timeout-duration: 3s
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 3s

