spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost/order-service
    username: user
    password: user
    jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: http://localhost:8716/eureka
