spring:
  application:
    name: inventory-service
  datasource:
    username: user
    password: user
    url: jdbc:mysql://localhost/inventory-service
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: http://localhost:8716/eureka